#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
if [[ "${TRACE-0}" == "1" ]]; then
  set -o xtrace
fi

(cd "$(pwd)/../roast-my-ui" \
  NODE_ENV=development pnpm install \
  node ace migration:run
)

pnpm run dev
